# Generated by Django 5.0.4 on 2024-06-05 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Enseignant', models.CharField(max_length=15)),
                ('prenom_Enseignant', models.CharField(max_length=15)),
                ('email_Enseignant', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_Cours', models.CharField(choices=[('FRANCAIS', 'Français'), ('ALLEMAND', 'Allemand'), ('ANGLAIS', 'Anglais'), ('MATHEMATIQUES', 'Mathématique'), ('PHYSIQUE CHIMIE', 'Physique chimie')], default=None, max_length=100)),
                ('date_Cours', models.DateField(blank=True, null=True)),
                ('durée_Cours', models.CharField(choices=[('1H30', '1H30'), ('3H', '3H')], default=None, max_length=100)),
                ('Enseignant', models.ForeignKey(db_column='Enseignant_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='ABS.enseignant')),
                ('groupe', models.ForeignKey(db_column='groupe_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='ABS.groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justifie', models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='NON', max_length=3)),
                ('justification', models.CharField(blank=True, max_length=100, null=True)),
                ('cours', models.ForeignKey(db_column='cours_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='ABS.cours')),
                ('etudiant', models.ForeignKey(db_column='etudiant_id', on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='ABS.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(db_column='groupe_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='ABS.groupe'),
        ),
    ]
